load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "registry",
    srcs = [
        "blobsizecache.go",
        "combined.go",
        "keepalive.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/pkg/serve/registry",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cas",
        "//pkg/registry",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/types",
    ],
)

go_test(
    name = "registry_test",
    srcs = [
        "blobsizecache_test.go",
        "keepalive_test.go",
    ],
    embed = [":registry"],
    deps = [
        "//pkg/cas",
        "//pkg/registry",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/types",
    ],
)
